# docker-compose -f database/start_db_docker-compose.yml up -d
# docker exec -it DMS-mysql /bin/bash
# docker-compose -f database/start_db_docker-compose.yml down

version: "3.9"

services:
    mysql-db:
        image: "mysql:8.0.26"
        container_name: DMS-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: DMS
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
        volumes:
            - ./db-data:/var/lib/mysql
        # entrypoint:
        #     sh -c "echo 'CREATE DATABASE IF NOT EXISTS DMS;' > /docker-entrypoint-initdb.d/init.sql;
        #         /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        ports:
            - "3010:3306"