# docker-compose -f database/start_db_docker-compose.yml up -d
# docker exec -it DMS-mysql /bin/bash
# docker-compose -f database/start_db_docker-compose.yml down

version: "3.9"

services:
    mysql-db:
        image: "mysql:8.0.26"
        container_name: DMS-mysql
        ports:
            - "3010:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: DMS
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
        volumes:
            - ./db-data:/var/lib/mysql
        # command: